================================================================ test session starts =================================================================
platform darwin -- Python 3.10.0b2, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /Users/jwr003/coding/pytest-fold/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/jwr003/coding/pytest-fold, configfile: pyproject.toml, testpaths: tests
collecting ... collected 19 items                                                                                                                                   

tests/test_pytest_fold.py::test_version PASSED                                                                                                 [  5%]
tests/test_pytest_fold.py::test_which_fails_1 FAILED                                                                                           [ 10%]
tests/test_pytest_fold.py::test_which_passes_1 PASSED                                                                                          [ 15%]
tests/test_pytest_fold.py::test_which_fails_2 FAILED                                                                                           [ 21%]
tests/test_pytest_fold.py::test_which_passes_2 PASSED                                                                                          [ 26%]
tests/test_pytest_fold.py::test_which_fails_3 FAILED                                                                                           [ 31%]
tests/test_pytest_fold.py::test_which_passes_3 PASSED                                                                                          [ 36%]
tests/test_pytest_fold.py::test_fail_1 FAILED                                                                                                  [ 42%]
tests/test_pytest_fold.py::test_fail_2 FAILED                                                                                                  [ 47%]
tests/test_pytest_fold.py::test_fail_3 FAILED                                                                                                  [ 52%]
tests/test_pytest_fold.py::test_pass_1 PASSED                                                                                                  [ 57%]
tests/test_pytest_fold.py::test_pass_2 PASSED                                                                                                  [ 63%]
tests/test_pytest_fold.py::test_pass_3 PASSED                                                                                                  [ 68%]
tests/test_pytest_fold.py::test_which_fails_and_has_stdout_1 FAILED                                                                            [ 73%]
tests/test_pytest_fold.py::test_which_pauses_and_fails_and_has_stdout_1 FAILED                                                                 [ 78%]
tests/test_pytest_fold.py::test_which_passes_and_has_stdout_2 PASSED                                                                           [ 84%]
tests/test_pytest_fold.py::test_summary PASSED                                                                                                 [ 89%]
tests/test_pytest_fold.py::test_fixture_for_fun_pass ERROR                                                                                     [ 94%]
tests/test_pytest_fold.py::test_fixture_for_fun_fail ERROR                                                                                     [100%]

======================================================================= ERRORS =======================================================================
____________________________________________________ ERROR at setup of test_fixture_for_fun_pass _____________________________________________________
file /Users/jwr003/coding/pytest-fold/tests/test_pytest_fold.py, line 132
  def test_fixture_for_fun_pass(fixture_for_fun):
E       fixture 'fixture_for_fun' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, fold, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/jwr003/coding/pytest-fold/tests/test_pytest_fold.py:132
____________________________________________________ ERROR at setup of test_fixture_for_fun_fail _____________________________________________________
file /Users/jwr003/coding/pytest-fold/tests/test_pytest_fold.py, line 135
  def test_fixture_for_fun_fail(fixture_for_fun):
E       fixture 'fixture_for_fun' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, fold, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/jwr003/coding/pytest-fold/tests/test_pytest_fold.py:135
====================================================================== FAILURES ======================================================================
_________________________________________________________________ test_which_fails_1 _________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_which_fails_1 [39;49;00m():
>        [94massert [39;49;00m  [94m0 [39;49;00m
E       assert 0

tests/test_pytest_fold.py:18: AssertionError
===MARKER2===
_________________________________________________________________ test_which_fails_2 _________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_which_fails_2 [39;49;00m():
>        [94massert [39;49;00m  [94m0 [39;49;00m
E       assert 0

tests/test_pytest_fold.py:26: AssertionError
===MARKER2===
_________________________________________________________________ test_which_fails_3 _________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_which_fails_3 [39;49;00m():
>        [94massert [39;49;00m  [94m0 [39;49;00m
E       assert 0

tests/test_pytest_fold.py:34: AssertionError
===MARKER2===
____________________________________________________________________ test_fail_1 _____________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_fail_1 [39;49;00m():
        a =  [94m0 [39;49;00m
        time.sleep( [94m0.05 [39;49;00m)
>        [94massert [39;49;00m  [94mFalse [39;49;00m
E       assert False

tests/test_pytest_fold.py:74: AssertionError
===MARKER2===
____________________________________________________________________ test_fail_2 _____________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_fail_2 [39;49;00m():
        a =  [94m0 [39;49;00m
        time.sleep( [94m0.05 [39;49;00m)
>        [94massert [39;49;00m  [94mFalse [39;49;00m
E       assert False

tests/test_pytest_fold.py:80: AssertionError
===MARKER2===
____________________________________________________________________ test_fail_3 _____________________________________________________________________

===MARKER1===
     [94mdef [39;49;00m  [92mtest_fail_3 [39;49;00m():
        a =  [94m0 [39;49;00m
        time.sleep( [94m0.05 [39;49;00m)
>        [94massert [39;49;00m  [94mFalse [39;49;00m
E       assert False

tests/test_pytest_fold.py:86: AssertionError
===MARKER2===
_________________________________________________________ test_which_fails_and_has_stdout_1 __________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x10e5d6d70>

===MARKER1===
     [94mdef [39;49;00m  [92mtest_which_fails_and_has_stdout_1 [39;49;00m(capsys):
         [96mprint [39;49;00m( [33m" [39;49;00m [33mthis test fails [39;49;00m [33m" [39;49;00m)
>        [94massert [39;49;00m  [94m0 [39;49;00m ==  [94m1 [39;49;00m
E       assert 0 == 1
E         +0
E         -1

tests/test_pytest_fold.py:109: AssertionError
===MARKER2===
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
this test fails
____________________________________________________ test_which_pauses_and_fails_and_has_stdout_1 ____________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x10e5e78e0>

===MARKER1===
     [94mdef [39;49;00m  [92mtest_which_pauses_and_fails_and_has_stdout_1 [39;49;00m(capsys):
         [96mprint [39;49;00m( [33m" [39;49;00m [33mthis test pauses, then fails [39;49;00m [33m" [39;49;00m)
        time.sleep( [94m2 [39;49;00m)
>        [94massert [39;49;00m  [94m0 [39;49;00m == - [94m11 [39;49;00m
E       assert 0 == -11
E         +0
E         --11

tests/test_pytest_fold.py:115: AssertionError
===MARKER2===
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
this test pauses, then fails
============================================================== short test summary info ===============================================================
FAILED tests/test_pytest_fold.py::test_which_fails_1 - assert 0
FAILED tests/test_pytest_fold.py::test_which_fails_2 - assert 0
FAILED tests/test_pytest_fold.py::test_which_fails_3 - assert 0
FAILED tests/test_pytest_fold.py::test_fail_1 - assert False
FAILED tests/test_pytest_fold.py::test_fail_2 - assert False
FAILED tests/test_pytest_fold.py::test_fail_3 - assert False
FAILED tests/test_pytest_fold.py::test_which_fails_and_has_stdout_1 - assert 0 == 1
FAILED tests/test_pytest_fold.py::test_which_pauses_and_fails_and_has_stdout_1 - assert 0 == -11
ERROR tests/test_pytest_fold.py::test_fixture_for_fun_pass
ERROR tests/test_pytest_fold.py::test_fixture_for_fun_fail
=======================================================  [31m [1m8 failed [0m,  [32m9 passed [0m,  [31m [1m2 errors [0m [31m in 2.47s [0m [31m ========================================================
